import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type {
	CatalogSourceMask,
	CatalogSourceMetadata,
} from "../src/tolgee/catalog-slices";
import {
	ALL_LANGUAGES,
	ALL_NAMESPACES,
	type Namespace,
} from "../src/tolgee/shared";

const root = fileURLToPath(new URL("../", import.meta.url));
type Tree = { [key: string]: Tree | string };

function at(tree: Tree, path: string[]): Tree | string | undefined {
	let value: Tree | string | undefined = tree;
	for (const key of path) {
		value = value && typeof value === "object" ? value[key] : undefined;
	}
	return value;
}

function metadata(locale: string): CatalogSourceMetadata {
	const raw = Object.fromEntries(
		ALL_NAMESPACES.map((namespace) => [
			namespace,
			JSON.parse(
				readFileSync(
					resolve(root, "messages", namespace, `${locale}.json`),
					"utf8",
				),
			) as Tree,
		]),
	) as Record<Namespace, Tree>;

	function shape(
		namespace: Namespace,
		tree: Tree,
		path: string[] = [],
	): CatalogSourceMask {
		return Object.fromEntries(
			Object.entries(tree).map(([key, child]) => {
				const next = [...path, key];
				const shared = ALL_NAMESPACES.some(
					(other) => other !== namespace && at(raw[other], next) !== undefined,
				);
				return [
					key,
					typeof child === "string" || !shared
						? 1
						: shape(namespace, child, next),
				];
			}),
		);
	}

	const contributors = new Map<string, Namespace[]>();
	function collect(
		namespace: Namespace,
		tree: Tree | string,
		path: string[] = [],
	) {
		if (typeof tree === "string") {
			const key = JSON.stringify(path);
			contributors.set(key, [...(contributors.get(key) ?? []), namespace]);
			return;
		}
		for (const [key, child] of Object.entries(tree))
			collect(namespace, child, [...path, key]);
	}
	for (const namespace of ALL_NAMESPACES) collect(namespace, raw[namespace]);

	return {
		sources: Object.fromEntries(
			ALL_NAMESPACES.map((namespace) => [
				namespace,
				shape(namespace, raw[namespace]),
			]),
		) as Record<Namespace, CatalogSourceMask>,
		collisions: Object.fromEntries(
			[...contributors].filter(([, sources]) => sources.length > 1),
		),
	};
}

// Share identical shapes without bundling catalog text into the client metadata.
const shapes = new Map<string, number>();
const locales = ALL_LANGUAGES.map((locale) => {
	const serialized = JSON.stringify(metadata(locale), null, "\t");
	if (!shapes.has(serialized)) shapes.set(serialized, shapes.size);
	return `\t${JSON.stringify(locale)}: sourceShape${shapes.get(serialized)},`;
});
const source = [
	"// Generated by pnpm i18n:metadata. Do not edit by hand.",
	'import type { CatalogSourceMetadata } from "./catalog-slices";',
	"",
	...[...shapes].map(
		([serialized, index]) =>
			`const sourceShape${index}: CatalogSourceMetadata = ${serialized};`,
	),
	"export const CATALOG_SOURCE_METADATA: Readonly<Record<string, CatalogSourceMetadata>> = {",
	...locales,
	"};",
	"",
].join("\n");
const output = resolve(root, "src/tolgee/catalog-source-metadata.generated.ts");
const formatted = execFileSync(
	process.execPath,
	[
		createRequire(import.meta.url).resolve("@biomejs/biome/bin/biome"),
		"format",
		"--stdin-file-path",
		output,
	],
	{ cwd: root, input: source, encoding: "utf8" },
);
let existing = "";
try {
	existing = readFileSync(output, "utf8");
} catch (error) {
	if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
}
if (existing !== formatted) writeFileSync(output, formatted);
console.log(
	`Catalog metadata: ${ALL_LANGUAGES.length} locales, ${shapes.size} distinct shapes.`,
);
