/**
 * A format-neutral report document for the table exporters (CSV, Excel, PDF):
 * a title, label/value facts, tables and notes. Builders turn report data into
 * one (`lib/reports/project-report-export.ts`); the exporters only render it,
 * so every format carries exactly the same figures. Client-safe.
 */

/**
 * How a column renders:
 * - `money`: an exact two-decimal string in the document's currency
 * - `hours`: hours as a number, shown with two decimals
 * - `count` / `percent`: whole numbers / a decimal string such as "52.7"
 */
export type ReportColumnKind = "text" | "hours" | "money" | "count" | "percent";

export interface ReportColumn {
	key: string;
	header: string;
	kind: ReportColumnKind;
}

/** `null` is an unknown value (cost unknown), rendered as the document's `unknownLabel`. */
export type ReportCell = string | number | null;

export interface ReportTable {
	/** Also the Excel sheet name (shortened to 31 characters). */
	title: string;
	columns: ReportColumn[];
	rows: ReportCell[][];
	/** A totals row, rendered last and emphasized. */
	totals?: ReportCell[];
}

export interface ReportDocument {
	title: string;
	/** Report facts: project, period, currency, when the rates were read, ... */
	facts: { label: string; value: string }[];
	tables: ReportTable[];
	/** Explanations printed under the tables (rounding rule, what "unknown" means). */
	notes: string[];
	/** What an unknown cell says, e.g. "Cost unknown". */
	unknownLabel: string;
	/** Basis of the download file name. */
	fileStem: string;
	/** Footer line, e.g. "Generated by Z8". */
	footer: string;
}

/** A cell as plain text, the way CSV and PDF show it. */
export function formatReportCell(
	cell: ReportCell,
	kind: ReportColumnKind,
	unknownLabel: string,
): string {
	if (cell === null) return unknownLabel;
	if (kind === "hours" && typeof cell === "number") return cell.toFixed(2);
	return String(cell);
}

/** A download file name: the stem as a slug, a timestamp and the extension. */
export function reportFileName(document: ReportDocument, extension: string, now = Date.now()): string {
	const stem =
		document.fileStem
			.normalize("NFKD")
			.replace(/[^a-z0-9]+/gi, "-")
			.replace(/^-+|-+$/g, "")
			.toLowerCase() || "report";
	return `${stem}-${now}.${extension}`;
}
