import type { TolgeeStaticData } from "@tolgee/react";
import {
	ALL_LANGUAGES,
	ALL_NAMESPACES,
	DEFAULT_LANGUAGE,
	type Namespace,
} from "./shared";

export type CatalogSlice = {
	locale: string;
	/** Complete namespace loads only. A partial shell projection has no loaded namespaces. */
	namespaces: readonly Namespace[];
	records: TolgeeStaticData;
	/** Only colliding primary leaves, keyed by JSON-encoded path segments (never dotted paths). */
	keyOwners: Readonly<Record<string, Namespace>>;
};

export function normalizeCatalogLocale(locale: string): string {
	return ALL_LANGUAGES.includes(locale) ? locale : DEFAULT_LANGUAGE;
}

export function canonicalizeNamespaces(
	namespaces: readonly Namespace[],
): readonly Namespace[] {
	for (const namespace of namespaces) {
		if (!ALL_NAMESPACES.includes(namespace)) {
			throw new Error(`Unsupported translation namespace: ${namespace}`);
		}
	}
	const selected = new Set(namespaces);
	// The cache identity and merge order both follow the predecessor's explicit priority.
	return ALL_NAMESPACES.filter((namespace) => selected.has(namespace));
}

// Generated from messages/*/*.json; catalog-slices.test.ts checks every locale.
// A terminal 1 denotes a leaf or a source-exclusive subtree.
export type CatalogSourceMask = {
	readonly [key: string]: CatalogSourceMask | 1;
};
type CatalogSourceMetadata = {
	sources: Readonly<Record<Namespace, CatalogSourceMask>>;
	collisions: Readonly<Record<string, readonly Namespace[]>>;
};
const sourceShape0: CatalogSourceMetadata = {
	sources: {
		common: {
			actions: 1,
			analytics: {
				export: 1,
			},
			appSearch: 1,
			billing: {
				suspended: 1,
				trialBanner: 1,
			},
			colors: 1,
			common: {
				actions: 1,
				active: 1,
				add: 1,
				adding: 1,
				all: 1,
				appName: 1,
				approve: 1,
				assign: 1,
				back: 1,
				cancel: 1,
				clear: 1,
				clearSearch: 1,
				clearSelection: 1,
				close: 1,
				confirm: 1,
				continue: 1,
				copy: 1,
				create: 1,
				current: 1,
				days: 1,
				delete: 1,
				deleting: 1,
				description: 1,
				deselectAll: 1,
				details: 1,
				download: 1,
				edit: 1,
				enabled: 1,
				error: 1,
				"error-occurred": 1,
				gender: 1,
				goToDashboard: 1,
				inactive: 1,
				loading: 1,
				loadMore: 1,
				months: 1,
				more: 1,
				moreActions: 1,
				moveDown: 1,
				moveUp: 1,
				name: 1,
				"new": 1,
				next: 1,
				notApplicable: 1,
				"not-available": 1,
				open: 1,
				openEnded: 1,
				openMenu: 1,
				optional: 1,
				or: 1,
				pending: 1,
				present: 1,
				previous: 1,
				recovering: 1,
				refresh: 1,
				refreshing: 1,
				reject: 1,
				rejecting: 1,
				remove: 1,
				removing: 1,
				reset: 1,
				retry: 1,
				save: 1,
				saveChanges: 1,
				saving: 1,
				selectAll: 1,
				selected: 1,
				"select-language": 1,
				set: 1,
				sets: 1,
				skip: 1,
				start: 1,
				status: 1,
				submitting: 1,
				sw: 1,
				to: 1,
				today: 1,
				unexpectedError: 1,
				unknown: 1,
				unknownEmployee: 1,
				unknownTeam: 1,
				unnamed: 1,
				update: 1,
				updating: 1,
				uploading: 1,
				validate: 1,
				validationError: 1,
				weekdays: 1,
				deployment: 1,
			},
			employeeSelect: 1,
			errors: 1,
			generic: 1,
			header: 1,
			info: 1,
			loading: 1,
			nav: 1,
			notifications: 1,
			offline: 1,
			presence: 1,
			roles: 1,
			status: 1,
			table: 1,
			time: 1,
			userAvatar: 1,
			user: 1,
			validation: 1,
			workBalance: 1,
			worksCouncil: 1,
		},
		admin: {
			admin: 1,
		},
		approvals: {
			approvals: 1,
			fastLanes: 1,
			sprint: 1,
		},
		auth: {
			auth: 1,
			profile: 1,
		},
		compliance: {
			compliance: 1,
		},
		analytics: {
			analytics: {
				access: 1,
				common: 1,
				layout: 1,
				overtimeBurnDown: 1,
				overview: 1,
				teamPerformance: 1,
				vacationTrends: 1,
				workHours: 1,
			},
		},
		dashboard: {
			dashboard: 1,
		},
		calendar: {
			absences: 1,
			calendar: 1,
		},
		timeTracking: {
			timeTracking: 1,
			wellness: 1,
		},
		reports: {
			reports: 1,
		},
		myRequests: {
			myRequests: 1,
		},
		payroll: {
			payroll: 1,
		},
		scheduling: {
			scheduling: 1,
		},
		setup: {
			init: 1,
			setup: 1,
		},
		"settings/generic": {
			settings: {
				avv: 1,
				billing: 1,
				compliance: 1,
				customDomains: 1,
				customers: 1,
				dataExport: 1,
				emailConfig: 1,
				emailTemplates: 1,
				error: 1,
				export: 1,
				exportOperations: 1,
				group: 1,
				implementationChecklist: 1,
				import: 1,
				licenses: 1,
				locations: 1,
				notifications: 1,
				organizations: 1,
				organization: 1,
				passkeys: 1,
				payrollAccess: 1,
				profile: 1,
				projects: 1,
				security: 1,
				sessions: 1,
				socialAccounts: 1,
				statistics: 1,
				timeFormat: 1,
				timezone: 1,
				title: 1,
				travelExpenses: 1,
				webhooks: 1,
				weekStart: 1,
				wellness: 1,
				workBalanceRecalculation: 1,
				workerQueue: 1,
				worksCouncil: 1,
			},
		},
		billing: {
			billing: {
				access: 1,
				activeSeats: 1,
				alerts: 1,
				bestValue: 1,
				billedMonthly: 1,
				cancelsOn: 1,
				checkoutCreateFailed: 1,
				checkoutStartFailed: 1,
				checkout: 1,
				choosePlan: 1,
				choosePlanDescription: 1,
				chooseUpgradePlanDescription: 1,
				currentPlan: 1,
				days: 1,
				description: 1,
				faq: 1,
				features: 1,
				interval: 1,
				manageBilling: 1,
				monthlyCost: 1,
				nextBilling: 1,
				opening: 1,
				perSeatMonth: 1,
				plans: 1,
				portalOpenFailed: 1,
				priceSeatMonth: 1,
				priceSeatMonthYearly: 1,
				seatBilledAnnually: 1,
				starting: 1,
				startTrial: 1,
				status: 1,
				title: 1,
				trialEnds: 1,
				upgradeMonthly: 1,
				upgradeYearly: 1,
				vatNotice: 1,
				yearTotal: 1,
			},
		},
		organization: {
			organization: 1,
		},
		team: {
			team: 1,
		},
		today: {
			today: 1,
		},
		travelExpenses: {
			travelExpenses: 1,
		},
		webhooks: {
			webhooks: 1,
		},
		"settings/enterprise": {
			settings: {
				apiKeys: 1,
				branding: 1,
				enterprise: 1,
				enterpriseIdentitySetup: 1,
			},
		},
		"settings/payrollExport": {
			settings: {
				payrollExport: 1,
				payrollReadiness: 1,
				workDiagnostics: 1,
			},
		},
		"settings/scheduledExports": {
			settings: {
				scheduledExports: 1,
			},
		},
		"settings/holidays": {
			settings: {
				holidays: 1,
			},
		},
		"settings/workPolicies": {
			settings: {
				timeRegulations: 1,
				workPolicies: 1,
				workSchedules: 1,
			},
		},
		"settings/vacation": {
			settings: {
				vacation: 1,
			},
			vacation: 1,
		},
		"settings/auditExport": {
			settings: {
				auditExport: 1,
				auditLog: 1,
			},
		},
		"settings/demo": {
			settings: {
				demo: 1,
				demoData: 1,
			},
		},
		"settings/rules": {
			settings: {
				absenceCategories: 1,
				approvalEscalation: 1,
				approvalPolicies: 1,
				changePolicies: 1,
				coverageRules: 1,
				shiftTemplates: 1,
				surcharges: 1,
				workCategories: 1,
			},
		},
		"settings/people": {
			settings: {
				employeeGroups: 1,
				employees: 1,
				employmentHistory: 1,
				inviteCodes: 1,
				managerAssignment: 1,
				pendingMembers: 1,
				permissions: 1,
				rateHistory: 1,
				roles: 1,
				skills: 1,
				teams: 1,
			},
		},
		"settings/integrations": {
			settings: {
				calendar: 1,
				clockinImport: 1,
				clockodoImport: 1,
				discord: 1,
				slack: 1,
				teamsNotifications: 1,
				telegram: 1,
			},
		},
		onboarding: {
			onboarding: 1,
		},
		bot: {
			bot: 1,
		},
		teamsBot: {
			approval: 1,
			commands: 1,
			common: {
				more: 1,
				moreBullet: 1,
			},
			digest: 1,
			exceptionTypes: 1,
		},
	},
	collisions: {
		'["common","more"]': ["common", "teamsBot"],
	},
};
const sourceShape1: CatalogSourceMetadata = {
	sources: {
		common: {
			actions: 1,
			analytics: {
				export: 1,
			},
			appSearch: 1,
			billing: {
				suspended: 1,
				trialBanner: 1,
			},
			colors: 1,
			common: {
				actions: 1,
				active: 1,
				add: 1,
				adding: 1,
				all: 1,
				appName: 1,
				approve: 1,
				assign: 1,
				back: 1,
				cancel: 1,
				clear: 1,
				clearSearch: 1,
				clearSelection: 1,
				close: 1,
				confirm: 1,
				continue: 1,
				copy: 1,
				create: 1,
				current: 1,
				days: 1,
				delete: 1,
				deleting: 1,
				description: 1,
				deselectAll: 1,
				details: 1,
				download: 1,
				edit: 1,
				enabled: 1,
				error: 1,
				"error-occurred": 1,
				gender: 1,
				goToDashboard: 1,
				inactive: 1,
				loading: 1,
				loadMore: 1,
				months: 1,
				more: 1,
				moreActions: 1,
				moveDown: 1,
				moveUp: 1,
				name: 1,
				"new": 1,
				next: 1,
				notApplicable: 1,
				"not-available": 1,
				open: 1,
				openEnded: 1,
				openMenu: 1,
				optional: 1,
				or: 1,
				pending: 1,
				present: 1,
				previous: 1,
				recovering: 1,
				refresh: 1,
				refreshing: 1,
				reject: 1,
				rejecting: 1,
				remove: 1,
				removing: 1,
				reset: 1,
				retry: 1,
				save: 1,
				saveChanges: 1,
				saving: 1,
				selectAll: 1,
				selected: 1,
				"select-language": 1,
				set: 1,
				sets: 1,
				skip: 1,
				start: 1,
				status: 1,
				submitting: 1,
				sw: 1,
				to: 1,
				today: 1,
				unexpectedError: 1,
				unknown: 1,
				unknownEmployee: 1,
				unknownTeam: 1,
				unnamed: 1,
				update: 1,
				updating: 1,
				uploading: 1,
				validate: 1,
				validationError: 1,
				weekdays: 1,
			},
			employeeSelect: 1,
			errors: 1,
			generic: 1,
			header: 1,
			info: 1,
			loading: 1,
			nav: 1,
			notifications: 1,
			offline: 1,
			presence: 1,
			roles: 1,
			status: 1,
			table: 1,
			time: 1,
			userAvatar: 1,
			user: 1,
			validation: 1,
			workBalance: 1,
			worksCouncil: 1,
		},
		admin: {
			admin: 1,
		},
		approvals: {
			approvals: 1,
			fastLanes: 1,
			sprint: 1,
		},
		auth: {
			auth: 1,
			profile: 1,
		},
		compliance: {
			compliance: 1,
		},
		analytics: {
			analytics: {
				access: 1,
				common: 1,
				layout: 1,
				overtimeBurnDown: 1,
				overview: 1,
				teamPerformance: 1,
				vacationTrends: 1,
				workHours: 1,
			},
		},
		dashboard: {
			dashboard: 1,
		},
		calendar: {
			absences: 1,
			calendar: 1,
		},
		timeTracking: {
			timeTracking: 1,
			wellness: 1,
		},
		reports: {
			reports: 1,
		},
		myRequests: {
			myRequests: 1,
		},
		payroll: {
			payroll: 1,
		},
		scheduling: {
			scheduling: 1,
		},
		setup: {
			init: 1,
			setup: 1,
		},
		"settings/generic": {
			settings: {
				avv: 1,
				billing: 1,
				compliance: 1,
				customDomains: 1,
				customers: 1,
				dataExport: 1,
				emailConfig: 1,
				emailTemplates: 1,
				error: 1,
				export: 1,
				exportOperations: 1,
				group: 1,
				implementationChecklist: 1,
				import: 1,
				licenses: 1,
				locations: 1,
				notifications: 1,
				organizations: 1,
				organization: 1,
				passkeys: 1,
				payrollAccess: 1,
				profile: 1,
				projects: 1,
				security: 1,
				sessions: 1,
				socialAccounts: 1,
				statistics: 1,
				timeFormat: 1,
				timezone: 1,
				title: 1,
				travelExpenses: 1,
				webhooks: 1,
				weekStart: 1,
				wellness: 1,
				workBalanceRecalculation: 1,
				workerQueue: 1,
				worksCouncil: 1,
			},
		},
		billing: {
			billing: {
				access: 1,
				activeSeats: 1,
				alerts: 1,
				bestValue: 1,
				billedMonthly: 1,
				cancelsOn: 1,
				checkoutCreateFailed: 1,
				checkoutStartFailed: 1,
				checkout: 1,
				choosePlan: 1,
				choosePlanDescription: 1,
				chooseUpgradePlanDescription: 1,
				currentPlan: 1,
				days: 1,
				description: 1,
				faq: 1,
				features: 1,
				interval: 1,
				manageBilling: 1,
				monthlyCost: 1,
				nextBilling: 1,
				opening: 1,
				perSeatMonth: 1,
				plans: 1,
				portalOpenFailed: 1,
				priceSeatMonth: 1,
				priceSeatMonthYearly: 1,
				seatBilledAnnually: 1,
				starting: 1,
				startTrial: 1,
				status: 1,
				title: 1,
				trialEnds: 1,
				upgradeMonthly: 1,
				upgradeYearly: 1,
				vatNotice: 1,
				yearTotal: 1,
			},
		},
		organization: {
			organization: 1,
		},
		team: {
			team: 1,
		},
		today: {
			today: 1,
		},
		travelExpenses: {
			travelExpenses: 1,
		},
		webhooks: {
			webhooks: 1,
		},
		"settings/enterprise": {
			settings: {
				apiKeys: 1,
				branding: 1,
				enterprise: 1,
				enterpriseIdentitySetup: 1,
			},
		},
		"settings/payrollExport": {
			settings: {
				payrollExport: 1,
				payrollReadiness: 1,
				workDiagnostics: 1,
			},
		},
		"settings/scheduledExports": {
			settings: {
				scheduledExports: 1,
			},
		},
		"settings/holidays": {
			settings: {
				holidays: 1,
			},
		},
		"settings/workPolicies": {
			settings: {
				timeRegulations: 1,
				workPolicies: 1,
				workSchedules: 1,
			},
		},
		"settings/vacation": {
			settings: {
				vacation: 1,
			},
			vacation: 1,
		},
		"settings/auditExport": {
			settings: {
				auditExport: 1,
				auditLog: 1,
			},
		},
		"settings/demo": {
			settings: {
				demo: 1,
				demoData: 1,
			},
		},
		"settings/rules": {
			settings: {
				absenceCategories: 1,
				approvalEscalation: 1,
				approvalPolicies: 1,
				changePolicies: 1,
				coverageRules: 1,
				shiftTemplates: 1,
				surcharges: 1,
				workCategories: 1,
			},
		},
		"settings/people": {
			settings: {
				employeeGroups: 1,
				employees: 1,
				employmentHistory: 1,
				inviteCodes: 1,
				managerAssignment: 1,
				pendingMembers: 1,
				permissions: 1,
				rateHistory: 1,
				roles: 1,
				skills: 1,
				teams: 1,
			},
		},
		"settings/integrations": {
			settings: {
				calendar: 1,
				clockinImport: 1,
				clockodoImport: 1,
				discord: 1,
				slack: 1,
				teamsNotifications: 1,
				telegram: 1,
			},
		},
		onboarding: {
			onboarding: 1,
		},
		bot: {
			bot: 1,
		},
		teamsBot: {
			approval: 1,
			commands: 1,
			common: {
				more: 1,
				moreBullet: 1,
			},
			digest: 1,
			exceptionTypes: 1,
		},
	},
	collisions: {
		'["common","more"]': ["common", "teamsBot"],
	},
};
export const CATALOG_SOURCE_METADATA: Readonly<
	Record<string, CatalogSourceMetadata>
> = {
	en: {
		...sourceShape0,
		sources: {
			...sourceShape0.sources,
			common: {
				...sourceShape0.sources.common,
				common: {
					...(sourceShape0.sources.common.common as CatalogSourceMask),
					brandLogo: 1,
					breadcrumb: 1,
					carousel: 1,
					datePicker: 1,
					durationMinutes: 1,
					fieldPresets: 1,
					focusInput: 1,
					loadingLabel: 1,
					loadingRegions: 1,
					notifications: 1,
					pagination: 1,
					sidebar: 1,
					timeInput: 1,
					worksCouncil: 1,
				},
			},
		},
	},
	de: {
		...sourceShape0,
		sources: {
			...sourceShape0.sources,
			common: {
				...sourceShape0.sources.common,
				common: {
					...(sourceShape0.sources.common.common as CatalogSourceMask),
					timeInput: 1,
				},
			},
		},
	},
	fr: sourceShape1,
	es: sourceShape1,
	it: sourceShape1,
	pt: sourceShape1,
	el: sourceShape1,
	pl: sourceShape1,
	tr: sourceShape1,
	gsw: sourceShape1,
};
