/**
 * Project report and customer view exports (#902): builds the format-neutral
 * report document that the CSV, Excel and PDF exporters render
 * (`exporters/report-document*.ts`). Client-safe.
 *
 * Exports only ever contain what the report data contains: cost and margin
 * are stripped at the data layer for project managers
 * (`lib/billable-time/report-figures.ts`), so their columns cannot appear.
 *
 * Figure groups are the seam for more figures: each group contributes columns
 * to every figure table (summary, employees, customers, projects) from the
 * rows' data. Hours and Billable Time figures are the groups today; invoiced
 * and un-invoiced figures (#903) are another group that reads its own optional
 * key on the same rows. Pass a longer group list, or append to
 * `PROJECT_REPORT_FIGURE_GROUPS`, without touching the exporters.
 */

import type { BillableFigures, InvoicingFigures } from "@/lib/billable-time/report-figures";
import type {
	ReportCell,
	ReportColumn,
	ReportDocument,
	ReportTable,
} from "./exporters/report-document";
import type {
	BillableTimeReportContext,
	CustomerBillableReport,
	ProjectDetailedReport,
} from "./project-types";

export interface ProjectReportExportLabels {
	projectReportTitle: string;
	customerReportTitle: string;
	project: string;
	customer: string;
	employee: string;
	date: string;
	period: string;
	generatedAt: string;
	currency: string;
	ratesResolvedAt: string;
	summaryTable: string;
	employeesTable: string;
	dailyHoursTable: string;
	customersTable: string;
	projectsTable: string;
	total: string;
	hours: string;
	workPeriods: string;
	billableHours: string;
	nonBillableHours: string;
	revenue: string;
	unpricedWork: string;
	unpricedHours: string;
	pendingReview: string;
	cost: string;
	margin: string;
	marginPercent: string;
	costUnknown: string;
	roundingNote: string;
	ratesNote: string;
	costUnknownNote: string;
	invoicedHours: string;
	invoicedRevenue: string;
	uninvoicedHours: string;
	uninvoicedRevenue: string;
	changedAfterInvoicing: string;
	invoicingNote: string;
	footer: string;
}

/** English labels; the UI passes translated ones. */
export const DEFAULT_PROJECT_REPORT_EXPORT_LABELS: ProjectReportExportLabels = {
	projectReportTitle: "Project report",
	customerReportTitle: "Customer report",
	project: "Project",
	customer: "Customer",
	employee: "Employee",
	date: "Date",
	period: "Period",
	generatedAt: "Generated on",
	currency: "Currency",
	ratesResolvedAt: "Rates as of",
	summaryTable: "Summary",
	employeesTable: "Employees",
	dailyHoursTable: "Hours per day",
	customersTable: "Customers",
	projectsTable: "Projects",
	total: "Total",
	hours: "Hours",
	workPeriods: "Work periods",
	billableHours: "Billable hours",
	nonBillableHours: "Non-billable hours",
	revenue: "Revenue",
	unpricedWork: "Unpriced work",
	unpricedHours: "Unpriced hours",
	pendingReview: "Pending corrections or submissions",
	cost: "Cost",
	margin: "Margin",
	marginPercent: "Margin %",
	costUnknown: "Cost unknown",
	roundingNote:
		"Amounts are summed exactly and rounded half up to the cent once per row; totals add up the rows.",
	ratesNote:
		"Revenue uses the rates in effect when the report was generated. Unpriced work has no rate and adds no revenue.",
	costUnknownNote:
		"Cost unknown: some of the work has no cost rate, so its cost and margin are not shown.",
	invoicedHours: "Invoiced hours",
	invoicedRevenue: "Invoiced revenue",
	uninvoicedHours: "Un-invoiced hours",
	uninvoicedRevenue: "Un-invoiced revenue",
	changedAfterInvoicing: "Changed after invoicing",
	invoicingNote:
		"Invoiced revenue keeps the rates of its invoice draft; un-invoiced revenue uses the rates in effect when the report was generated.",
	footer: "Generated by Z8",
};

export interface ProjectReportExportContext {
	labels: ProjectReportExportLabels;
	/** When the export was made, already formatted for display. */
	generatedAt: string;
}

/** The figures of one table row, whatever the row is (project, employee, customer). */
export interface ReportFigureRow {
	totalMinutes: number;
	workPeriodCount: number;
	billable?: BillableFigures;
}

export interface ReportFigureColumn extends ReportColumn {
	value(row: ReportFigureRow): ReportCell;
}

/** A group of figure columns derived from the rows it renders. */
export interface ReportFigureGroup {
	id: string;
	columns(
		rows: readonly ReportFigureRow[],
		context: ProjectReportExportContext & { currency: string | null },
	): ReportFigureColumn[];
}

const hours = (minutes: number) => Math.round((minutes / 60) * 100) / 100;

export const hoursFigureGroup: ReportFigureGroup = {
	id: "hours",
	columns: (_rows, { labels }) => [
		{ key: "hours", header: labels.hours, kind: "hours", value: (row) => hours(row.totalMinutes) },
		{
			key: "workPeriods",
			header: labels.workPeriods,
			kind: "count",
			value: (row) => row.workPeriodCount,
		},
	],
};

/** Billable Time figures; cost and margin only when the rows carry them. */
export const billableFigureGroup: ReportFigureGroup = {
	id: "billable",
	columns: (rows, { labels, currency }) => {
		if (!rows.some((row) => row.billable)) return [];
		const money = (label: string) => (currency ? `${label} (${currency})` : label);
		const figure = (read: (figures: BillableFigures) => ReportCell) => (row: ReportFigureRow) =>
			row.billable ? read(row.billable) : "";
		const columns: ReportFigureColumn[] = [
			{
				key: "billableHours",
				header: labels.billableHours,
				kind: "hours",
				value: figure((f) => hours(f.billableMinutes)),
			},
			{
				key: "nonBillableHours",
				header: labels.nonBillableHours,
				kind: "hours",
				value: figure((f) => hours(f.nonBillableMinutes)),
			},
			{
				key: "revenue",
				header: money(labels.revenue),
				kind: "money",
				value: figure((f) => f.revenue),
			},
			{
				key: "unpricedWork",
				header: labels.unpricedWork,
				kind: "count",
				value: figure((f) => f.unpricedWorkCount),
			},
			{
				key: "unpricedHours",
				header: labels.unpricedHours,
				kind: "hours",
				value: figure((f) => Math.round(f.unpricedHours * 100) / 100),
			},
			{
				key: "pendingReview",
				header: labels.pendingReview,
				kind: "count",
				value: figure((f) => f.pendingReviewCount),
			},
		];
		if (rows.some((row) => row.billable?.access === "full")) {
			const full = (read: (figures: Extract<BillableFigures, { access: "full" }>) => ReportCell) =>
				figure((f) => (f.access === "full" ? read(f) : ""));
			columns.push(
				{ key: "cost", header: money(labels.cost), kind: "money", value: full((f) => f.cost) },
				{
					key: "margin",
					header: money(labels.margin),
					kind: "money",
					value: full((f) => f.margin),
				},
				{
					key: "marginPercent",
					header: labels.marginPercent,
					kind: "percent",
					value: full((f) => f.marginPercent ?? (f.margin === null ? null : "")),
				},
			);
		}
		return columns;
	},
};

/** Invoiced and un-invoiced figures (#903), when the rows' Billable Time figures carry them. */
export const invoicingFigureGroup: ReportFigureGroup = {
	id: "invoicing",
	columns: (rows, { labels, currency }) => {
		if (!rows.some((row) => row.billable?.invoicing)) return [];
		const money = (label: string) => (currency ? `${label} (${currency})` : label);
		const figure = (read: (figures: InvoicingFigures) => ReportCell) => (row: ReportFigureRow) =>
			row.billable?.invoicing ? read(row.billable.invoicing) : "";
		return [
			{
				key: "invoicedHours",
				header: labels.invoicedHours,
				kind: "hours",
				value: figure((f) => hours(f.invoicedMinutes)),
			},
			{
				key: "invoicedRevenue",
				header: money(labels.invoicedRevenue),
				kind: "money",
				value: figure((f) => f.invoicedRevenue),
			},
			{
				key: "uninvoicedHours",
				header: labels.uninvoicedHours,
				kind: "hours",
				value: figure((f) => hours(f.uninvoicedMinutes)),
			},
			{
				key: "uninvoicedRevenue",
				header: money(labels.uninvoicedRevenue),
				kind: "money",
				value: figure((f) => f.uninvoicedRevenue),
			},
			{
				key: "changedAfterInvoicing",
				header: labels.changedAfterInvoicing,
				kind: "count",
				value: figure((f) => f.changedAfterInvoicingCount),
			},
		];
	},
};

/** The figure groups every project report and customer view export renders, in order. */
export const PROJECT_REPORT_FIGURE_GROUPS: readonly ReportFigureGroup[] = [
	hoursFigureGroup,
	billableFigureGroup,
	invoicingFigureGroup,
];

interface FigureTableInput<Row extends ReportFigureRow> {
	title: string;
	/** Leading text columns, such as the employee or the customer and project. */
	leading: { key: string; header: string; value: (row: Row) => string }[];
	rows: readonly Row[];
	totals?: { label: string; row: ReportFigureRow };
}

function figureTable<Row extends ReportFigureRow>(
	input: FigureTableInput<Row>,
	groups: readonly ReportFigureGroup[],
	context: ProjectReportExportContext & { currency: string | null },
): ReportTable {
	const figureRows: ReportFigureRow[] = [
		...input.rows,
		...(input.totals ? [input.totals.row] : []),
	];
	const figureColumns = groups.flatMap((group) => group.columns(figureRows, context));
	const columns: ReportColumn[] = [
		...input.leading.map(({ key, header }) => ({ key, header, kind: "text" as const })),
		...figureColumns.map(({ key, header, kind }) => ({ key, header, kind })),
	];
	return {
		title: input.title,
		columns,
		rows: input.rows.map((row) => [
			...input.leading.map((column) => column.value(row)),
			...figureColumns.map((column) => column.value(row)),
		]),
		...(input.totals
			? {
					totals: [
						input.totals.label,
						...input.leading.slice(1).map(() => ""),
						...figureColumns.map((column) => column.value(input.totals?.row as ReportFigureRow)),
					],
				}
			: {}),
	};
}

const dayOf = (isoInstant: string) => isoInstant.slice(0, 10);

function billableFacts(
	billableTime: BillableTimeReportContext | undefined,
	labels: ProjectReportExportLabels,
) {
	return billableTime
		? [
				{ label: labels.currency, value: billableTime.currency },
				{ label: labels.ratesResolvedAt, value: billableTime.ratesResolvedAt },
			]
		: [];
}

function billableNotes(
	rows: readonly ReportFigureRow[],
	labels: ProjectReportExportLabels,
): string[] {
	if (!rows.some((row) => row.billable)) return [];
	const notes = [labels.roundingNote, labels.ratesNote];
	if (rows.some((row) => row.billable?.invoicing)) notes.push(labels.invoicingNote);
	if (rows.some((row) => row.billable?.access === "full")) notes.push(labels.costUnknownNote);
	return notes;
}

/** The export document of one project's detailed report. */
export function buildProjectReportDocument(
	report: ProjectDetailedReport,
	context: ProjectReportExportContext,
	groups: readonly ReportFigureGroup[] = PROJECT_REPORT_FIGURE_GROUPS,
): ReportDocument {
	const { labels } = context;
	const tableContext = { ...context, currency: report.billableTime?.currency ?? null };
	const summaryRow: ReportFigureRow & { name: string } = {
		name: report.project.name,
		totalMinutes: report.summary.totalMinutes,
		workPeriodCount: report.summary.workPeriodCount,
		billable: report.summary.billable,
	};
	return {
		title: `${labels.projectReportTitle} – ${report.project.name}`,
		facts: [
			{ label: labels.project, value: report.project.name },
			...(report.project.customer
				? [{ label: labels.customer, value: report.project.customer.name }]
				: []),
			{
				label: labels.period,
				value: `${dayOf(report.period.startDate)} – ${dayOf(report.period.endDate)}`,
			},
			{ label: labels.generatedAt, value: context.generatedAt },
			...billableFacts(report.billableTime, labels),
		],
		tables: [
			figureTable(
				{
					title: labels.summaryTable,
					leading: [{ key: "project", header: labels.project, value: (row) => row.name }],
					rows: [summaryRow],
				},
				groups,
				tableContext,
			),
			figureTable(
				{
					title: labels.employeesTable,
					leading: [{ key: "employee", header: labels.employee, value: (row) => row.employeeName }],
					rows: report.employeeBreakdown,
					totals: { label: labels.total, row: summaryRow },
				},
				groups,
				tableContext,
			),
			{
				title: labels.dailyHoursTable,
				columns: [
					{ key: "date", header: labels.date, kind: "text" },
					{ key: "hours", header: labels.hours, kind: "hours" },
				],
				rows: report.timeSeries.map((point) => [point.date, Math.round(point.hours * 100) / 100]),
			},
		],
		notes: billableNotes([summaryRow], labels),
		unknownLabel: labels.costUnknown,
		fileStem: `project-report-${report.project.name}`,
		footer: `${labels.footer} | ${context.generatedAt}`,
	};
}

/** The export document of the customer view. */
export function buildCustomerReportDocument(
	view: CustomerBillableReport,
	context: ProjectReportExportContext,
	groups: readonly ReportFigureGroup[] = PROJECT_REPORT_FIGURE_GROUPS,
): ReportDocument {
	const { labels } = context;
	const tableContext = { ...context, currency: view.billableTime.currency };
	const projects = view.customers.flatMap((row) =>
		row.projects.map((project) => ({ ...project, customerName: row.customer.name })),
	);
	return {
		title: labels.customerReportTitle,
		facts: [
			{
				label: labels.period,
				value: `${dayOf(view.period.startDate)} – ${dayOf(view.period.endDate)}`,
			},
			{ label: labels.generatedAt, value: context.generatedAt },
			...billableFacts(view.billableTime, labels),
		],
		tables: [
			figureTable(
				{
					title: labels.customersTable,
					leading: [
						{ key: "customer", header: labels.customer, value: (row) => row.customer.name },
					],
					rows: view.customers,
					totals: { label: labels.total, row: view.totals },
				},
				groups,
				tableContext,
			),
			figureTable(
				{
					title: labels.projectsTable,
					leading: [
						{ key: "customer", header: labels.customer, value: (row) => row.customerName },
						{ key: "project", header: labels.project, value: (row) => row.project.name },
					],
					rows: projects,
				},
				groups,
				tableContext,
			),
		],
		notes: billableNotes([view.totals], labels),
		unknownLabel: labels.costUnknown,
		fileStem: "customer-report",
		footer: `${labels.footer} | ${context.generatedAt}`,
	};
}
