// @ts-nocheck
import { default as __fd_glob_85 } from "../content/docs/tech/technical/meta.json?collection=meta"
import { default as __fd_glob_84 } from "../content/docs/tech/deployment/meta.json?collection=meta"
import { default as __fd_glob_83 } from "../content/docs/guide/user-guide/meta.json?collection=meta"
import { default as __fd_glob_82 } from "../content/docs/guide/getting-started/meta.json?collection=meta"
import { default as __fd_glob_81 } from "../content/docs/guide/manager-guide/meta.json?collection=meta"
import { default as __fd_glob_80 } from "../content/docs/guide/admin-guide/meta.json?collection=meta"
import { default as __fd_glob_79 } from "../content/docs/desktop/getting-started/meta.json?collection=meta"
import { default as __fd_glob_78 } from "../content/docs/desktop/troubleshooting/meta.json?collection=meta"
import { default as __fd_glob_77 } from "../content/docs/desktop/features/meta.json?collection=meta"
import { default as __fd_glob_76 } from "../content/docs/tech/meta.json?collection=meta"
import { default as __fd_glob_75 } from "../content/docs/guide/meta.json?collection=meta"
import { default as __fd_glob_74 } from "../content/docs/desktop/meta.json?collection=meta"
import { default as __fd_glob_73 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_72 from "../content/docs/tech/technical/testing.mdx?collection=docs"
import * as __fd_glob_71 from "../content/docs/tech/technical/services.mdx?collection=docs"
import * as __fd_glob_70 from "../content/docs/tech/technical/index.mdx?collection=docs"
import * as __fd_glob_69 from "../content/docs/tech/technical/getting-started.mdx?collection=docs"
import * as __fd_glob_68 from "../content/docs/tech/technical/features.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/tech/technical/enterprise.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/tech/technical/database.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/tech/technical/authentication.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/tech/deployment/index.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/guide/admin-guide/work-policies.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/guide/admin-guide/work-categories.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/guide/admin-guide/webhooks.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/guide/admin-guide/troubleshooting.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/guide/admin-guide/time-regulations.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/guide/admin-guide/telemetry.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/guide/admin-guide/teams.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/guide/admin-guide/teams-integration.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/guide/admin-guide/system-administration.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/guide/admin-guide/surcharges.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/guide/admin-guide/social-oauth.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/guide/admin-guide/skills-qualifications.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/guide/admin-guide/scim-provisioning.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/guide/admin-guide/schedules.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/guide/admin-guide/projects.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/guide/admin-guide/project-reports.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/guide/admin-guide/platform-admin.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/guide/admin-guide/permissions.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/guide/admin-guide/payroll-export.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/guide/admin-guide/manager-assignments.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/guide/admin-guide/locations.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/guide/admin-guide/index.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/guide/admin-guide/holidays-and-vacation.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/guide/admin-guide/employee-management.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/guide/admin-guide/conditional-access.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/guide/admin-guide/compliance-radar.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/guide/admin-guide/change-policies.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/guide/admin-guide/app-access-control.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/guide/admin-guide/api-keys.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/guide/admin-guide/analytics-and-exports.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/guide/user-guide/wellness.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/guide/user-guide/vacation.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/guide/user-guide/time-tracking.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/guide/user-guide/notifications.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/guide/user-guide/language-preferences.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/guide/user-guide/index.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/guide/user-guide/getting-started.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/guide/user-guide/faq.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/guide/user-guide/desktop-app.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/guide/user-guide/calendar.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/guide/user-guide/calendar-sync.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/guide/user-guide/browser-extension.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/guide/user-guide/account-security.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/guide/manager-guide/index.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/guide/manager-guide/coverage-targets.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/guide/getting-started/index.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/desktop/troubleshooting/platform-specific.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/desktop/troubleshooting/index.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/desktop/troubleshooting/common-issues.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/desktop/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/desktop/getting-started/index.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/desktop/getting-started/first-steps.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/desktop/getting-started/authentication.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/desktop/features/time-tracking.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/desktop/features/system-tray.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/desktop/features/settings.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/desktop/features/organizations.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/desktop/features/offline-mode.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/desktop/features/index.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/desktop/features/idle-detection.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/tech/index.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/guide/index.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/desktop/index.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.doc("docs", "content/docs", {"index.mdx": __fd_glob_0, "desktop/index.mdx": __fd_glob_1, "guide/index.mdx": __fd_glob_2, "tech/index.mdx": __fd_glob_3, "desktop/features/idle-detection.mdx": __fd_glob_4, "desktop/features/index.mdx": __fd_glob_5, "desktop/features/offline-mode.mdx": __fd_glob_6, "desktop/features/organizations.mdx": __fd_glob_7, "desktop/features/settings.mdx": __fd_glob_8, "desktop/features/system-tray.mdx": __fd_glob_9, "desktop/features/time-tracking.mdx": __fd_glob_10, "desktop/getting-started/authentication.mdx": __fd_glob_11, "desktop/getting-started/first-steps.mdx": __fd_glob_12, "desktop/getting-started/index.mdx": __fd_glob_13, "desktop/getting-started/installation.mdx": __fd_glob_14, "desktop/troubleshooting/common-issues.mdx": __fd_glob_15, "desktop/troubleshooting/index.mdx": __fd_glob_16, "desktop/troubleshooting/platform-specific.mdx": __fd_glob_17, "guide/getting-started/index.mdx": __fd_glob_18, "guide/manager-guide/coverage-targets.mdx": __fd_glob_19, "guide/manager-guide/index.mdx": __fd_glob_20, "guide/user-guide/account-security.mdx": __fd_glob_21, "guide/user-guide/browser-extension.mdx": __fd_glob_22, "guide/user-guide/calendar-sync.mdx": __fd_glob_23, "guide/user-guide/calendar.mdx": __fd_glob_24, "guide/user-guide/desktop-app.mdx": __fd_glob_25, "guide/user-guide/faq.mdx": __fd_glob_26, "guide/user-guide/getting-started.mdx": __fd_glob_27, "guide/user-guide/index.mdx": __fd_glob_28, "guide/user-guide/language-preferences.mdx": __fd_glob_29, "guide/user-guide/notifications.mdx": __fd_glob_30, "guide/user-guide/time-tracking.mdx": __fd_glob_31, "guide/user-guide/vacation.mdx": __fd_glob_32, "guide/user-guide/wellness.mdx": __fd_glob_33, "guide/admin-guide/analytics-and-exports.mdx": __fd_glob_34, "guide/admin-guide/api-keys.mdx": __fd_glob_35, "guide/admin-guide/app-access-control.mdx": __fd_glob_36, "guide/admin-guide/change-policies.mdx": __fd_glob_37, "guide/admin-guide/compliance-radar.mdx": __fd_glob_38, "guide/admin-guide/conditional-access.mdx": __fd_glob_39, "guide/admin-guide/employee-management.mdx": __fd_glob_40, "guide/admin-guide/holidays-and-vacation.mdx": __fd_glob_41, "guide/admin-guide/index.mdx": __fd_glob_42, "guide/admin-guide/locations.mdx": __fd_glob_43, "guide/admin-guide/manager-assignments.mdx": __fd_glob_44, "guide/admin-guide/payroll-export.mdx": __fd_glob_45, "guide/admin-guide/permissions.mdx": __fd_glob_46, "guide/admin-guide/platform-admin.mdx": __fd_glob_47, "guide/admin-guide/project-reports.mdx": __fd_glob_48, "guide/admin-guide/projects.mdx": __fd_glob_49, "guide/admin-guide/schedules.mdx": __fd_glob_50, "guide/admin-guide/scim-provisioning.mdx": __fd_glob_51, "guide/admin-guide/skills-qualifications.mdx": __fd_glob_52, "guide/admin-guide/social-oauth.mdx": __fd_glob_53, "guide/admin-guide/surcharges.mdx": __fd_glob_54, "guide/admin-guide/system-administration.mdx": __fd_glob_55, "guide/admin-guide/teams-integration.mdx": __fd_glob_56, "guide/admin-guide/teams.mdx": __fd_glob_57, "guide/admin-guide/telemetry.mdx": __fd_glob_58, "guide/admin-guide/time-regulations.mdx": __fd_glob_59, "guide/admin-guide/troubleshooting.mdx": __fd_glob_60, "guide/admin-guide/webhooks.mdx": __fd_glob_61, "guide/admin-guide/work-categories.mdx": __fd_glob_62, "guide/admin-guide/work-policies.mdx": __fd_glob_63, "tech/deployment/index.mdx": __fd_glob_64, "tech/technical/authentication.mdx": __fd_glob_65, "tech/technical/database.mdx": __fd_glob_66, "tech/technical/enterprise.mdx": __fd_glob_67, "tech/technical/features.mdx": __fd_glob_68, "tech/technical/getting-started.mdx": __fd_glob_69, "tech/technical/index.mdx": __fd_glob_70, "tech/technical/services.mdx": __fd_glob_71, "tech/technical/testing.mdx": __fd_glob_72, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_73, "desktop/meta.json": __fd_glob_74, "guide/meta.json": __fd_glob_75, "tech/meta.json": __fd_glob_76, "desktop/features/meta.json": __fd_glob_77, "desktop/troubleshooting/meta.json": __fd_glob_78, "desktop/getting-started/meta.json": __fd_glob_79, "guide/admin-guide/meta.json": __fd_glob_80, "guide/manager-guide/meta.json": __fd_glob_81, "guide/getting-started/meta.json": __fd_glob_82, "guide/user-guide/meta.json": __fd_glob_83, "tech/deployment/meta.json": __fd_glob_84, "tech/technical/meta.json": __fd_glob_85, });