apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: marketing
  namespace: app-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: app-prod-marketing-ip-allowlist@kubernetescrd,app-prod-redirect-to-www@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - www.z8-time.app
        - z8-time.app
      secretName: marketing-tls
  rules:
    - host: www.z8-time.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marketing
                port:
                  number: 80
    - host: z8-time.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: marketing
                port:
                  number: 80
