apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telemetry
  namespace: app-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - telemetry.z8-time.app
      secretName: telemetry-tls
  rules:
    - host: telemetry.z8-time.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: telemetry-external
                port:
                  number: 3000
