apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: web-forwarded-headers
  namespace: app-prod
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: ui.z8-time.app
      X-Forwarded-Proto: https
