/**
 * The timesheet of a hand-off (#903): the itemized work behind one invoice
 * draft as it was handed off, as a format-neutral report document that the
 * existing CSV and PDF exporters render (`lib/reports/exporters`). Client-safe.
 */

import { parseUnits } from "@/lib/money/exact-decimal";
import type { ReportDocument } from "@/lib/reports/exporters/report-document";
import type { TimesheetRowView } from "./views";

export interface TimesheetLabels {
	title: string;
	customer: string;
	period: string;
	generatedAt: string;
	table: string;
	date: string;
	employee: string;
	project: string;
	start: string;
	end: string;
	hours: string;
	total: string;
	note: string;
	footer: string;
}

/** English labels; the UI passes translated ones. */
export const DEFAULT_TIMESHEET_LABELS: TimesheetLabels = {
	title: "Timesheet",
	customer: "Customer",
	period: "Period",
	generatedAt: "Generated on",
	table: "Work",
	date: "Date",
	employee: "Employee",
	project: "Project",
	start: "Start",
	end: "End",
	hours: "Hours",
	total: "Total",
	note: "Times are local to where the work was recorded. Hours are rounded to two decimals per work period.",
	footer: "Generated by Z8",
};

export function buildTimesheetDocument(
	draft: {
		customerName: string;
		period: { from: string; to: string };
		timesheet: readonly TimesheetRowView[];
	},
	context: { labels: TimesheetLabels; generatedAt: string },
): ReportDocument {
	const { labels } = context;
	const totalHundredths = draft.timesheet.reduce(
		(sum, row) => sum + Number(parseUnits(row.hours, 2) ?? BigInt(0)),
		0,
	);
	return {
		title: `${labels.title} – ${draft.customerName}`,
		facts: [
			{ label: labels.customer, value: draft.customerName },
			{ label: labels.period, value: `${draft.period.from} – ${draft.period.to}` },
			{ label: labels.generatedAt, value: context.generatedAt },
		],
		tables: [
			{
				title: labels.table,
				columns: [
					{ key: "date", header: labels.date, kind: "text" },
					{ key: "employee", header: labels.employee, kind: "text" },
					{ key: "project", header: labels.project, kind: "text" },
					{ key: "start", header: labels.start, kind: "text" },
					{ key: "end", header: labels.end, kind: "text" },
					{ key: "hours", header: labels.hours, kind: "hours" },
				],
				rows: draft.timesheet.map((row) => [
					row.day,
					row.employeeName,
					row.projectName,
					row.start,
					row.end,
					Number(row.hours),
				]),
				totals: [labels.total, "", "", "", "", totalHundredths / 100],
			},
		],
		notes: [labels.note],
		unknownLabel: "",
		fileStem: `timesheet-${draft.customerName}-${draft.period.from}-${draft.period.to}`,
		footer: `${labels.footer} | ${context.generatedAt}`,
	};
}
