// Writes the per-build settings Capacitor does not manage itself:
// - www/shell-config.js: the origin the offline page returns to.
// - ios/App/App/Info.plist: WKAppBoundDomains, so the service worker runs on iOS.
// Run before `cap sync` (the `sync` script does this).
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolveShellSettings, withAppBoundDomains } from "../shell-config.ts";

const settings = resolveShellSettings(process.env);
const appDirectory = new URL("../", import.meta.url);

writeFileSync(
	new URL("www/shell-config.js", appDirectory),
	`// Generated by scripts/prepare-shell.ts. Do not edit.\nwindow.Z8_SHELL = ${JSON.stringify({ origin: settings.origin })};\n`,
);

const infoPlist = new URL("ios/App/App/Info.plist", appDirectory);
if (existsSync(infoPlist)) {
	const current = readFileSync(infoPlist, "utf8");
	const patched = withAppBoundDomains(current, settings.appBoundDomains);
	if (patched !== current) {
		writeFileSync(infoPlist, patched);
	}
}

console.log(
	`Z8 shell: ${settings.origin} (app-bound domains: ${settings.appBoundDomains.join(", ")})`,
);
