"use client";

import { IconDownload, IconFileSpreadsheet, IconFileText } from "@tabler/icons-react";
import { useTranslate } from "@tolgee/react";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { useDisplayContext } from "@/hooks/use-display-context";
import { systemClock } from "@/lib/datetime/temporal-core";
import { formatInstant } from "@/lib/datetime/temporal-format";
import { type ReportDocument, reportFileName } from "@/lib/reports/exporters/report-document";
import { exportReportDocumentToCSV } from "@/lib/reports/exporters/report-document-csv";
import type {
	ProjectReportExportContext,
	ProjectReportExportLabels,
} from "@/lib/reports/project-report-export";

export type ExportFormat = "pdf" | "excel" | "csv";

/** The export labels in the viewer's language. */
export function useProjectReportExportLabels(): ProjectReportExportLabels {
	const { t } = useTranslate();
	return {
		projectReportTitle: t("reports.projects.export.projectReportTitle", "Project report"),
		customerReportTitle: t("reports.projects.export.customerReportTitle", "Customer report"),
		project: t("reports.projects.export.project", "Project"),
		customer: t("reports.projects.export.customer", "Customer"),
		employee: t("reports.projects.export.employee", "Employee"),
		date: t("reports.projects.export.date", "Date"),
		period: t("reports.projects.export.period", "Period"),
		generatedAt: t("reports.projects.export.generatedAt", "Generated on"),
		currency: t("reports.projects.export.currency", "Currency"),
		ratesResolvedAt: t("reports.projects.export.ratesResolvedAt", "Rates as of"),
		summaryTable: t("reports.projects.export.summaryTable", "Summary"),
		employeesTable: t("reports.projects.export.employeesTable", "Employees"),
		dailyHoursTable: t("reports.projects.export.dailyHoursTable", "Hours per day"),
		customersTable: t("reports.projects.export.customersTable", "Customers"),
		projectsTable: t("reports.projects.export.projectsTable", "Projects"),
		total: t("reports.projects.export.total", "Total"),
		hours: t("reports.projects.export.hours", "Hours"),
		workPeriods: t("reports.projects.export.workPeriods", "Work periods"),
		billableHours: t("reports.projects.export.billableHours", "Billable hours"),
		nonBillableHours: t("reports.projects.export.nonBillableHours", "Non-billable hours"),
		withoutCustomerHours: t(
			"reports.projects.export.withoutCustomerHours",
			"Billable hours without customer",
		),
		withoutCustomer: t("reports.projects.export.withoutCustomer", "Without customer"),
		revenue: t("reports.projects.export.revenue", "Revenue"),
		unpricedWork: t("reports.projects.export.unpricedWork", "Unpriced work"),
		unpricedHours: t("reports.projects.export.unpricedHours", "Unpriced hours"),
		pendingReview: t("reports.projects.export.pendingReview", "Pending corrections or submissions"),
		cost: t("reports.projects.export.cost", "Cost"),
		margin: t("reports.projects.export.margin", "Margin"),
		marginPercent: t("reports.projects.export.marginPercent", "Margin %"),
		costUnknown: t("reports.projects.export.costUnknown", "Cost unknown"),
		roundingNote: t(
			"reports.projects.export.roundingNote",
			"Amounts are summed exactly and rounded half up to the cent once per row; totals add up the rows.",
		),
		ratesNote: t(
			"reports.projects.export.ratesNote",
			"Revenue uses the rates in effect when the report was generated. Unpriced work has no rate and adds no revenue.",
		),
		costUnknownNote: t(
			"reports.projects.export.costUnknownNote",
			"Cost unknown: some of the work has no cost rate, so its cost and margin are not shown.",
		),
		invoicedHours: t("reports.projects.export.invoicedHours", "Invoiced hours"),
		invoicedRevenue: t("reports.projects.export.invoicedRevenue", "Invoiced revenue"),
		uninvoicedHours: t("reports.projects.export.uninvoicedHours", "Un-invoiced hours"),
		uninvoicedRevenue: t("reports.projects.export.uninvoicedRevenue", "Un-invoiced revenue"),
		changedAfterInvoicing: t(
			"reports.projects.export.changedAfterInvoicing",
			"Changed after invoicing",
		),
		invoicingNote: t(
			"reports.projects.export.invoicingNote",
			"Invoiced revenue keeps the rates of its invoice draft; un-invoiced revenue uses the rates in effect when the report was generated.",
		),
		footer: t("reports.projects.export.footer", "Generated by Z8"),
	};
}

interface ReportDocumentExportButtonsProps {
	/** Builds the document to export from the viewer's labels. */
	buildDocument: (context: ProjectReportExportContext) => ReportDocument;
	/** The formats offered (default: PDF, Excel and CSV). */
	formats?: readonly ExportFormat[];
}

/**
 * CSV, Excel and PDF export of a report document (project report, customer
 * view). The document comes from report data the server already filtered for
 * the viewer, so the files carry nothing the screen does not.
 */
export function ReportDocumentExportButtons({
	buildDocument,
	formats = ["pdf", "excel", "csv"],
}: ReportDocumentExportButtonsProps) {
	const { t } = useTranslate();
	const displayContext = useDisplayContext();
	const labels = useProjectReportExportLabels();
	const [loading, setLoading] = useState<ExportFormat | null>(null);

	const handleExport = async (format: ExportFormat) => {
		setLoading(format);
		const generatedAt = formatInstant(systemClock.nowInstant(), displayContext, "dateTimeMedium");
		try {
			const document = buildDocument({ labels, generatedAt });
			const file =
				format === "pdf"
					? {
							data: await (
								await import("@/lib/reports/exporters/report-document-pdf")
							).exportReportDocumentToPDF(document),
							filename: reportFileName(document, "pdf"),
							mimeType: "application/pdf",
						}
					: format === "excel"
						? {
								data: await (
									await import("@/lib/reports/exporters/report-document-excel")
								).exportReportDocumentToExcel(document),
								filename: reportFileName(document, "xlsx"),
								mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
							}
						: {
								data: exportReportDocumentToCSV(document),
								filename: reportFileName(document, "csv"),
								mimeType: "text/csv;charset=utf-8;",
							};
			const blob = new Blob([file.data as BlobPart], { type: file.mimeType });
			const url = URL.createObjectURL(blob);
			const anchor = window.document.createElement("a");
			anchor.href = url;
			anchor.download = file.filename;
			window.document.body.appendChild(anchor);
			anchor.click();
			window.document.body.removeChild(anchor);
			URL.revokeObjectURL(url);
			toast.success(t("reports.export.success", "Export successful"), {
				description: t("reports.export.downloaded", "Downloaded {filename}", {
					filename: file.filename,
				}),
			});
		} catch (error) {
			console.error("Export failed:", error);
			toast.error(t("reports.export.failed", "Export failed"), {
				description:
					error instanceof Error
						? error.message
						: t("reports.export.errorDescription", "An error occurred while exporting the report"),
			});
		} finally {
			setLoading(null);
		}
	};

	return (
		<div className="flex flex-wrap gap-2">
			{formats.includes("pdf") && (
				<Button onClick={() => handleExport("pdf")} disabled={loading !== null} variant="outline">
					<IconFileText className="mr-2 size-4" />
					{loading === "pdf"
						? t("reports.export.generating", "Generating...")
						: t("reports.export.pdf", "Export PDF")}
				</Button>
			)}
			{formats.includes("excel") && (
				<Button onClick={() => handleExport("excel")} disabled={loading !== null} variant="outline">
					<IconFileSpreadsheet className="mr-2 size-4" />
					{loading === "excel"
						? t("reports.export.generating", "Generating...")
						: t("reports.export.excel", "Export Excel")}
				</Button>
			)}
			{formats.includes("csv") && (
				<Button onClick={() => handleExport("csv")} disabled={loading !== null} variant="outline">
					<IconDownload className="mr-2 size-4" />
					{loading === "csv"
						? t("reports.export.generating", "Generating...")
						: t("reports.export.csv", "Export CSV")}
				</Button>
			)}
		</div>
	);
}
