"use client";
import { IconCircleCheck, IconRefresh, IconRotateClockwise, IconShieldCheck, IconTrash } from "@tabler/icons-react";
import { useTranslate } from "@tolgee/react";
import type { EnterpriseIdentitySetupResponse } from "@/app/[locale]/(app)/settings/enterprise/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScimCredentialList } from "./scim-credential-list";
import { ScimDestructiveDialogs } from "./scim-destructive-dialogs";
import { ScimEventsList } from "./scim-events-list";
import { ScimOneTimeCredentialDialog } from "./scim-one-time-credential-dialog";
import { useScimAdminController } from "./use-scim-admin-controller";

export function ScimStep({ initialSetup }: { initialSetup: EnterpriseIdentitySetupResponse }) {
	const { t } = useTranslate(); const controller = useScimAdminController(initialSetup); const roleId = initialSetup.state.scim.policy.defaultRoleTemplateId ?? initialSetup.defaultRoleTemplateId;
	const state = !controller.connectionId ? "disconnected" : !controller.status ? "active-unverified" : controller.status.connection.decommissionedAt ? "decommissioned" : controller.status.connection.decommissionStartedAt ? "decommissioning" : controller.status.credentials.some((entry) => entry.lastUsedAt) ? "verified" : "active-unverified";
	const displayedState = controller.pendingAction === "create" ? "creating" : controller.pendingAction === "rotate" ? "rotating" : controller.pendingAction === "refresh" ? "refreshing" : controller.pendingAction === "revoke" ? "revoking" : controller.pendingAction === "decommission" ? "decommissioning" : controller.lifecycle ?? state;
	return <section className="min-w-0 space-y-4" data-scim-state={displayedState}>
		<div className="rounded-lg border bg-muted/20 p-4"><div className="flex min-w-0 flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><IconShieldCheck className="size-5 text-primary" aria-hidden="true" /><h3 className="font-semibold">{t("settings.enterprise.identity.scim.title", "SCIM Provisioning")}</h3></div><p className="mt-1 text-muted-foreground text-sm">{t("settings.enterprise.identity.scim.description", "Connect your identity provider to provision and manage workforce access.")}</p></div><Badge className="w-fit">{displayedState.replaceAll("_", " ").replaceAll("-", " ")}</Badge></div><dl className="mt-4 grid min-w-0 gap-3 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">Endpoint</dt><dd translate="no" className="break-all font-mono">/api/auth/scim/v2</dd></div><div><dt className="text-muted-foreground">Credential expiry</dt><dd>1 year</dd></div><div><dt className="text-muted-foreground">Verification</dt><dd>{state === "verified" ? "Observed" : "Awaiting provider use"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2">{displayedState === "decommissioned" ? null : !controller.connectionId ? <Button type="button" disabled={!roleId || controller.isPending || displayedState === "creating"} onClick={() => controller.create(roleId)}>{displayedState === "creating" ? "Creating SCIM connection" : !roleId ? "Select a default role template first" : "Create SCIM connection"}</Button> : <><Button type="button" variant="outline" onClick={controller.refresh} disabled={controller.isPending || displayedState === "decommissioning"}><IconRefresh className="mr-2 size-4" aria-hidden="true" />Refresh status</Button><Button type="button" onClick={controller.rotate} disabled={controller.isPending || displayedState === "decommissioning"}><IconRotateClockwise className="mr-2 size-4" aria-hidden="true" />Rotate credential</Button><Button type="button" variant="destructive" onClick={controller.requestDecommission} disabled={controller.isPending || displayedState === "decommissioning"}><IconTrash className="mr-2 size-4" aria-hidden="true" />Decommission</Button></>}</div></div>
		{controller.status ? <><div className="space-y-2"><h4 className="font-medium text-sm">Credentials</h4><ScimCredentialList credentials={controller.status.credentials} pending={controller.isPending} onRevoke={controller.requestRevoke} /></div><div className="space-y-2"><h4 className="font-medium text-sm">Recent Events</h4><ScimEventsList events={controller.events} error={controller.eventsError} /></div></> : controller.connectionId ? <p className="flex items-center gap-2 rounded-lg border p-3 text-muted-foreground text-sm"><IconCircleCheck className="size-4" aria-hidden="true" />Refresh status to load safe connection metadata.</p> : null}
		<ScimOneTimeCredentialDialog credential={controller.credential} open={controller.credential !== null} onClosed={controller.clearCredential} /><ScimDestructiveDialogs action={controller.destructive} onCancel={controller.cancelDestructive} onConfirm={controller.confirm} />
	</section>;
}
