import {
	IconAddressBook,
	IconBeach,
	IconBell,
	IconBriefcase,
	IconBuilding,
	IconCalendarClock,
	IconCalendarEvent,
	IconCalendarShare,
	IconCertificate,
	IconChartBar,
	IconClock,
	IconClockEdit,
	IconCreditCard,
	IconDatabaseExport,
	IconDroplet,
	IconFileText,
	IconGavel,
	IconHistory,
	IconKey,
	IconMail,
	IconMapPin,
	IconPercentage,
	IconRadar,
	IconServer,
	IconShield,
	IconShieldCheck,
	IconTag,
	IconTarget,
	IconTestPipe,
	IconUserCircle,
	IconUsers,
	IconWebhook,
	IconWorld,
} from "@tabler/icons-react";
import type { SettingsIconName } from "./settings-config";

export const SETTINGS_ICON_MAP: Record<
	SettingsIconName,
	React.ComponentType<{ className?: string }>
> = {
	"address-book": IconAddressBook,
	"user-circle": IconUserCircle,
	shield: IconShield,
	"shield-check": IconShieldCheck,
	bell: IconBell,
	droplet: IconDroplet,
	building: IconBuilding,
	users: IconUsers,
	"map-pin": IconMapPin,
	"calendar-event": IconCalendarEvent,
	"calendar-clock": IconCalendarClock,
	beach: IconBeach,
	clock: IconClock,
	"clock-edit": IconClockEdit,
	gavel: IconGavel,
	percentage: IconPercentage,
	briefcase: IconBriefcase,
	world: IconWorld,
	history: IconHistory,
	"chart-bar": IconChartBar,
	"database-export": IconDatabaseExport,
	"test-pipe": IconTestPipe,
	mail: IconMail,
	tag: IconTag,
	server: IconServer,
	key: IconKey,
	webhook: IconWebhook,
	"calendar-sync": IconCalendarShare,
	radar: IconRadar,
	target: IconTarget,
	certificate: IconCertificate,
	"credit-card": IconCreditCard,
	"file-text": IconFileText,
};
